//! Blueprint file format definitions and conversion utilities
//!
//! This module defines the serialization formats for blueprint files, including
//! the main BlueprintAsset format and helper structures for format conversion.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use ui::graph::{
    BlueprintMetadata, ClassVariable, GraphDescription, GraphViewState, SubGraphDefinition,
};

/// Serializable event definition (mirrors core::graph::EventDefinition).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventDefDescription {
    pub uid: String,
    pub name: String,
    pub fields: Vec<EventFieldDescription>,
    pub return_type: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventFieldDescription {
    pub name: String,
    pub type_name: String,
}

// ============================================================================
// Main Blueprint Asset Format
// ============================================================================

/// The unified blueprint file format containing all blueprint data.
/// This is the primary format used for saving and loading blueprint files.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlueprintAsset {
    /// Format version for forward/backward compatibility
    pub format_version: u32,

    /// The main event graph for this blueprint
    pub main_graph: GraphDescription,

    /// Local macro definitions (subgraphs)
    pub local_macros: Vec<SubGraphDefinition>,

    /// Local event definitions
    #[serde(default)]
    pub local_events: Vec<EventDefDescription>,

    /// Class variables for this blueprint
    pub variables: Vec<ClassVariable>,

    /// Editor state (open tabs, view positions, etc.)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub editor_state: Option<BlueprintEditorState>,

    /// Metadata about the blueprint itself
    #[serde(default)]
    pub blueprint_metadata: BlueprintMetadata,
}

impl BlueprintAsset {
    /// Create a new empty blueprint asset
    pub fn new() -> Self {
        Self {
            format_version: 1,
            main_graph: GraphDescription::new("EventGraph"),
            local_macros: Vec::new(),
            local_events: Vec::new(),
            variables: Vec::new(),
            editor_state: None,
            blueprint_metadata: BlueprintMetadata::default(),
        }
    }

    /// Create a blueprint asset from components
    pub fn from_components(
        main_graph: GraphDescription,
        local_macros: Vec<SubGraphDefinition>,
        local_events: Vec<EventDefDescription>,
        variables: Vec<ClassVariable>,
        editor_state: Option<BlueprintEditorState>,
    ) -> Self {
        Self {
            format_version: 1,
            main_graph,
            local_macros,
            local_events,
            variables,
            editor_state,
            blueprint_metadata: BlueprintMetadata::default(),
        }
    }
}

impl Default for BlueprintAsset {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// Editor State
// ============================================================================

/// Editor state for restoring the exact UI configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlueprintEditorState {
    /// IDs of currently open tabs (in order)
    pub open_tab_ids: Vec<String>,

    /// Index of the active tab
    pub active_tab_index: usize,

    /// View state (pan/zoom) for each graph by tab ID
    pub graph_view_states: HashMap<String, GraphViewState>,
}

impl BlueprintEditorState {
    /// Create a new editor state
    pub fn new() -> Self {
        Self {
            open_tab_ids: vec!["main".to_string()],
            active_tab_index: 0,
            graph_view_states: HashMap::new(),
        }
    }

    /// Add a tab to the editor state
    pub fn add_tab(&mut self, tab_id: String) {
        if !self.open_tab_ids.contains(&tab_id) {
            self.open_tab_ids.push(tab_id);
        }
    }

    /// Set view state for a tab
    pub fn set_view_state(&mut self, tab_id: String, view_state: GraphViewState) {
        self.graph_view_states.insert(tab_id, view_state);
    }
}

impl Default for BlueprintEditorState {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// Serialization Helpers
// ============================================================================

/// Generate a file header comment for blueprint files
pub fn generate_file_header() -> String {
    let now = chrono::Local::now();
    let version = ui::ENGINE_VERSION;

    format!(
        "// Auto Generated by the Pulsar Blueprint Editor\n\
         // DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN\n\
         // Generated on {} - Engine version {}\n\
         //\n\
         // This file contains the COMPLETE blueprint for this class including:\n\
         //   - Main event graph\n\
         //   - All local macro graphs\n\
         //   - Class variables\n\
         //   - Editor state (open tabs, camera positions, etc.)\n\
         //\n\
         // You can modify the graph by opening this class in the Pulsar Blueprint Editor.\n\
         // The graph is saved in JSON format for human readability and version control.\n\
         //\n\
         // EDITING THE JSON STRUCTURE COULD BREAK THE EDITOR\n\
         // AND PREVENT THE GUI FROM OPENING THIS CLASS - BE CAREFUL\n\n",
        now.format("%Y-%m-%d %H:%M:%S"),
        version
    )
}

/// Strip header comments from a file's content
pub fn strip_header_comments(content: &str) -> String {
    content
        .lines()
        .skip_while(|line| line.trim().starts_with("//"))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Serialize a blueprint asset to JSON string with header
pub fn serialize_blueprint_with_header(asset: &BlueprintAsset) -> Result<String, String> {
    let json = serde_json::to_string_pretty(asset)
        .map_err(|e| format!("Failed to serialize blueprint: {}", e))?;

    Ok(format!("{}{}", generate_file_header(), json))
}

/// Deserialize a blueprint asset from JSON string (with or without header)
pub fn deserialize_blueprint(content: &str) -> Result<BlueprintAsset, String> {
    let json = strip_header_comments(content);

    serde_json::from_str::<BlueprintAsset>(&json)
        .map_err(|e| format!("Failed to deserialize blueprint: {}", e))
}

// ============================================================================
// Format Version Checking
// ============================================================================

/// Check if a blueprint format version is supported
pub fn is_version_supported(version: u32) -> bool {
    version == 1 // Currently only version 1 is supported
}

/// Get the current blueprint format version
pub fn current_format_version() -> u32 {
    1
}
