//! Blueprint persistence uses the shared, headless schema.
pub use blueprint_graph::{BlueprintAsset, BlueprintEditorState, EventDefDescription, EventFieldDescription};

// ============================================================================
// Serialization Helpers
// ============================================================================

/// Generate a file header comment for blueprint files
pub fn generate_file_header() -> String {
    let now = chrono::Local::now();
    let version = ui::ENGINE_VERSION;

    format!(
        "// Auto Generated by the Pulsar Blueprint Editor\n\
         // DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN\n\
         // Generated on {} - Engine version {}\n\
         //\n\
         // This file contains the COMPLETE blueprint for this class including:\n\
         //   - Main event graph\n\
         //   - All local macro graphs\n\
         //   - Class variables\n\
         //   - Editor state (open tabs, camera positions, etc.)\n\
         //\n\
         // You can modify the graph by opening this class in the Pulsar Blueprint Editor.\n\
         // The graph is saved in JSON format for human readability and version control.\n\
         //\n\
         // EDITING THE JSON STRUCTURE COULD BREAK THE EDITOR\n\
         // AND PREVENT THE GUI FROM OPENING THIS CLASS - BE CAREFUL\n\n",
        now.format("%Y-%m-%d %H:%M:%S"),
        version
    )
}

pub use blueprint_graph::codec::{strip_header_comments, deserialize_blueprint, is_version_supported, current_format_version};

/// Serialize a blueprint asset to JSON string with header
pub fn serialize_blueprint_with_header(asset: &BlueprintAsset) -> Result<String, String> {
    let json = serde_json::to_string_pretty(asset)
        .map_err(|e| format!("Failed to serialize blueprint: {}", e))?;

    Ok(format!("{}{}", generate_file_header(), json))
}

